menu:
- {name: 'Qui sommes nous ?',       url: 'qui-sommes-nous'}
- {name: 'Le lieu',  url: 'lieu'}
- {name: 'Nos propositions', url: 'propositions'}
- {name: 'Nos soutiens',      url: 'soutiens'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter', link:    'https://twitter.com/paululele'}
- {icon: 'facebook', link:   'https://www.facebook.com/lacabane.education'}
#- {icon: 'instagram', link:  'https://instagram.com/paululele'}
#- {icon: 'linkedin', link: 'https://fr.linkedin.com/'}
- {icon: 'envelope', link:   'mailto:contact@lacabane.education'}

sharing_button_prompt: 'Feel free to share!'
